version: "3"
services:
    postgres:
        image: postgres:11-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - 5432:5432
    mongo:
        image: mongo
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        ports:
            - 27017:27017
    mysql:
        image: mysql:5.7
        container_name: kode-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
    redis:
        image: redis
        container_name: kode-redis
        ports:
            - 6379:6379
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
